# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9c0d956cae24c1c336445692ede23a8dbafec1c0accd60675bce0e32209e9dd447c4562bcacdb83f97c1176593aa9ea26e857156332db4a73db520abba011c35

test:
  secret_key_base: 72195578985b12a9487a4d66e072e954a8743a167d182fea445c989a15887c9a5f1ba8c979f1c7cac9e35c811d6260e028a9a4d15e9a2bea1b71a7b446e12f53

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
